# Subject : Access Tuple Items in  python  
# Author : Muhammad Qamar
# Date : 19-july-2025


# Access Tuple Items
# this_tuple = ("apple",'banana','cherry',"apple",'banana','cherry',"apple",'banana','kiwi')
# print(this_tuple[1])
# print(this_tuple[-1])
# print(this_tuple[0])

# print(this_tuple[:])
# print(this_tuple[2:])
# print(this_tuple[2:6])
# print(this_tuple[:6])


this_tuple = ("apple",'banana','cherry',"apple",'banana','cherry',"apple",'banana','kiwi',"mango")
# print(this_tuple[::-1])

if 'mango' in this_tuple:
    print("yes it is present")
